
stages:
  - build

# format:
#   stage: test
#   script:
#     - go fmt $(go list ./... | grep -v /vendor/)
#     - go vet $(go list ./... | grep -v /vendor/)
#     - go test -race $(go list ./... | grep -v /vendor/)

compile:
  image: golang:1.18
  stage: build
  script:
    - go build -o ./cmd/socks5lb
  artifacts:
    paths:
      - socks5lb
